# 本番環境用

# サービス指定
version: '3'

# サービス定義
services:
  python:
    expose: # コンテナ間の連携で疎通させるポート
    - "5000"
    environment: # 環境変数の設定
    - DJANGO_SETTINGS_MODULE=djangoPJ.settings.product
  webserver:
    ports: # ホストのポート:コンテナのポート疎通
    - "80:80"
    volumes: # nginxの設定ファイルをマウント
    - ./web_server/product.conf:/etc/nginx/conf.d/default.conf


